name: trix
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - six=1.15.0
  - protobuf=3.20.1
  - biopython=1.78
  - rich=13.3
  - matplotlib=3.6
  - numpy=1.25
  - python-codon-tables=0.1
  - python-dotenv=0.21
  - scikit-learn=1.2
  - tenacity=8.2
  - tensorboard=2.11
  - tensorboardX=2.2
  - tqdm=4.64
  - pip=22.3.1
  - pre_commit=3.4.0
  - matplotlib=3.6
  - joblib=1.2.0
  - regex=2023.10.3
  - dm-tree=0.1.7
  - jupyter=1.0.0
  - scipy=1.12.0
  - jupyterlab=4.0.11
  - jupyterlab_code_formatter=2.2.1
  - pandas=1.5.2
  - pip:
      - --find-links https://storage.googleapis.com/jax-releases/libtpu_releases.html
      - --find-links https://download.pytorch.org/whl/torch_stable.html
      - -r requirements.txt
